language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - curl -sS http://getcomposer.org/installer | php
    - php composer.phar install --dev --prefer-source --no-interaction

script: phpunit --coverage-text --coverage-clover ./build/logs/clover.xml

after_script: php vendor/bin/coveralls
